[package]
name = "dsii"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
tokio = { version = "1.47.1", features = ["macros", "parking_lot", "rt-multi-thread", "signal"] }
zbus = { version = "5.10.0", default-features = false, features = ["tokio"] }
